Vagrant.configure(2) do |config|

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "puppet/environments"
    puppet.environment = "vagrant"
  end

  config.vm.define "debian6" do |debian6|
    debian6.vm.box = "puppetlabs/debian-6.0.10-64-puppet"
    debian6.vm.hostname = "debian6.box"
  end

  config.vm.define "debian7" do |debian7|
    debian7.vm.box = "puppetlabs/debian-7.8-64-puppet"
    debian7.vm.hostname = "debian7.box"
  end

  config.vm.define "debian8" do |debian8|
    debian8.vm.box = "puppetlabs/debian-8.2-64-puppet"
    debian8.vm.hostname = "debian8.box"
  end

  config.vm.define "el6" do |el6|
    el6.vm.box = "puppetlabs/centos-6.6-64-puppet"
    el6.vm.hostname = "el6.box"
  end

  config.vm.define "el7" do |el7|
    el7.vm.box = "puppetlabs/centos-7.0-64-puppet"
    el7.vm.hostname = "el7.box"
  end

  config.vm.define "ubuntu1404" do |ubuntu1404|
    ubuntu1404.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    ubuntu1404.vm.hostname = "ubuntu1404.box"
  end

end
